name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: |
          echo "=================================="
          echo " Deploy JavaScript App 🚀"
          echo " Deployment successful ✅"
          echo "=================================="
